### ISSUE TITLE
Me salía 1 sola casilla...

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/CalculadoraBinaria#8]
...no sé que hacer, si que mi bot organizador me pueda ayudar, hice toda la documentación necesaria!

Saludos!!

**Comment by Autinfit** [comment]
Estimado cliente:

Tal vez faltaba agregar una línea de código que permite distanciar casilla por casilla para que pueda aparecer solamente 9 de ellas:

x += 60

Espero te sirva de ayuda y que funcione de mejor forma tu código!

Saludos!

**Comment by MARSFOREVER472** [comment]
AHORA SÍ!!!!!!

MUCHAS GRACIAS POR TU AYUDA!!!!!
